services:
  mysql:
   image: mysql
   ports:
      - "3306:3306"

   expose:
      - "3306"
   environment:
     MYSQL_USER=admin
     MYSQL_PASSWORD=P4o3l8l1
     MYSQL_DATABASE=Banco
     MYSQL_ROOT_PASSWORD=P4o3l8l1
